#ifndef JOGO_DA_VELHA_FORMATACAO_PRINT_H
#define JOGO_DA_VELHA_FORMATACAO_PRINT_H

#define RESET "\033[00m"
#define GREEN "\033[32m"
#define RED "\033[31m"
#define YELLOW ""

#endif //JOGO_DA_VELHA_REDES_FUNCOES_GENERICAS_H