CC = gcc

all:
	$(CC) jogo_da_velha_redes_funcoes_genericas.cpp jogo_da_velha_redes_servidor.cpp -o server
	$(CC) jogo_da_velha_redes_funcoes_genericas.cpp jogo_da_velha_redes_cliente.cpp -o client

clean:
	rm server
	rm client